name: Build OTServ 8.0 (64-bit)

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repozytorium do sklonowania'
        required: true
        default: 'https://github.com/opentibia/server.git'
      ref:
        description: 'Gałąź/tag/commit (zostaw puste, żeby wziąć domyślną gałąź)'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies (VS2019 + CMake + Git)
        shell: pwsh
        run: |
          choco install -y visualstudio2019buildtools `
            --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 `
            --add Microsoft.VisualStudio.Component.Windows10SDK.18362"
          choco install -y cmake git
          cmake --version

      - name: Clone OTServ source
        shell: pwsh
        run: |
          if ("${{ github.event.inputs.ref }}") {
            git clone --depth 1 --branch "${{ github.event.inputs.ref }}" "${{ github.event.inputs.repo_url }}" source
          } else {
            git clone --depth 1 "${{ github.event.inputs.repo_url }}" source
          }

      - name: Configure (CMake x64 Release, VS2019, C++11)
        shell: pwsh
        run: |
          cd source
          mkdir build
          cd build
          # Używamy klasycznej składni "cmake .." (bez -S/-B), ustawiamy C++11 i policy minimum
          cmake .. -G "Visual Studio 16 2019" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF `
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        shell: pwsh
        run: |
          cd source/build
          cmake --build . --config Release --parallel

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: otserv-exe
          path: |
            source/build/Release/otserv.exe
            source/build/otserv.exe

