name: Build OTS (Windows x64, MinGW)

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source OTS repo (user/repo)'
        required: true
        default: 'opentibiabr/otservbr-global-archived'
      source_ref:
        description: 'Branch/tag/commit of OTS repo'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup MSYS2 (MINGW64) + deps
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-boost-headers
          mingw-w64-x86_64-boost-libs
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-SDL2_ttf

    - name: Clone OTServ source (fast)
      shell: msys2 {0}
      run: |
        git clone --depth=1 --branch "${{ github.event.inputs.source_ref }}" https://github.com/${{ github.event.inputs.source_repo }} source

    - name: Configure (CMake Release, MinGW, SQLite=ON)
      shell: msys2 {0}
      run: |
        cmake -S source -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_SQLITE=ON \
          -DBOOST_ROOT=/mingw64 \
          -DBOOST_INCLUDEDIR=/mingw64/include \
          -DBOOST_LIBRARYDIR=/mingw64/lib

    - name: Build (cmake --build)
      shell: msys2 {0}
      run: cmake --build build --parallel

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: otserv-executable
        path: build/theforgottenserver.exe
