name: Build OTServ 8.0 (Windows x64, MinGW)

on:
  workflow_dispatch:
    inputs:
      self_ref:
        description: 'Gałąź tego repo (tibia8-server), z której ma pójść workflow'
        default: 'main'
        required: true
      source_repo:
        description: 'Repozytorium ze źródłami OTServ do sklonowania'
        default: 'opentibiabr/otservbr-global-archived'
        required: true
      source_ref:
        description: 'Gałąź/tag/commit źródeł OTServ'
        default: 'develop'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Ten checkout jest tylko po to, by pobrać bieżący workflow z wybranej gałęzi tego repo
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.self_ref }}

      - name: Setup MSYS2 (MINGW64) + deps
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-sqlite3

      # Szybkie klonowanie źródeł OTServ (z repo i gałęzi podanych przy uruchamianiu)
      - name: Clone OTServ source (fast)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.source_ref }}
          path: source
          fetch-depth: 1
          lfs: false

      - name: Configure (CMake Release, MinGW, SQLite=ON)
        shell: bash
        run: |
          cmake -S source -B build \
            -G "MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SQLITE=ON

      - name: Build (cmake --build)
        shell: bash
        run: |
          cmake --build build --config Release -j"$(nproc || echo 4)"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: otserv-windows-x64-sqlite
          path: |
            build/*.exe
            build/*.dll
            build/*.pdb
          if-no-files-found: warn
