name: Build OTServ 8.0 (Windows x64, MinGW)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64) + deps
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-sqlite3

      # <<< TO JEST NOWY, SZYBKI KROK KLONOWANIA >>>
      - name: Clone OTServ source (fast)
        uses: actions/checkout@v4
with:
  repository: opentibiabr/otservbr-global-archived
  ref: develop
  path: source
  fetch-depth: 1
  lfs: false


      - name: Configure (CMake Release, MinGW, SQLite=ON)
        shell: bash
        run: |
          cmake -S source -B build \
            -G "MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SQLITE=ON

      - name: Build (cmake --build)
        shell: bash
        run: |
          cmake --build build --config Release -j"$(nproc || echo 4)"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: otserv-windows-x64-sqlite
          path: |
            build/*.exe
            build/*.dll
            build/*.pdb
          if-no-files-found: warn
``
