name: Build OTS (Windows x64)

on:
  workflow_dispatch:
    inputs:
      ots_repo:
        description: 'Repozytorium OTS (np. opentibiabr/otservbr-global-archived)'
        required: true
        default: 'opentibiabr/otservbr-global-archived'
      ots_branch:
        description: 'Gałąź/tag/commit (np. develop)'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-sqlite3
            cryptopp

      - name: Sync pacman and install missing dependencies
        shell: msys2 {0}
        run: |
          pacman -Syu --noconfirm

      - name: Clone OTS source
        shell: msys2 {0}
        run: |
          git clone https://github.com/${{ github.event.inputs.ots_repo }} --branch ${{ github.event.inputs.ots_branch }} --depth 1 src

      - name: Configure with CMake
        shell: msys2 {0}
        run: |
          cmake -S src -B build -G "MinGW Makefiles" -DUSE_SQLITE=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build with mingw32-make
        shell: msys2 {0}
        run: |
          cmake --build build --config Release

      - name: List build output
        shell: msys2 {0}
        run: |
          ls -R build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: otserv-executable
          path: build/
