name: Build OTServ 8.0 (Linux x64)

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repozytorium do sklonowania'
        required: true
        default: 'https://github.com/opentibia/server.git'
      ref:
        description: 'Gałąź/tag/commit (zostaw puste, żeby wziąć domyślną gałąź)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libssl-dev liblua5.1-0-dev zlib1g-dev

      - name: Clone OTServ source
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.ref }}" ]; then
            git clone --depth 1 --branch "${{ github.event.inputs.ref }}" "${{ github.event.inputs.repo_url }}" source
          else
            git clone --depth 1 "${{ github.event.inputs.repo_url }}" source
          fi

      - name: Configure (CMake Release, GCC)
        shell: bash
        env:
          CMAKE_ARGS: ""   # wyczyść ewentualne globalne -S/-B
        run: |
          cd source
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        shell: bash
        run: |
          cd source/build
          cmake --build . --config Release --parallel

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: otserv-linux
          path: |
            source/build/otserv
            source/build/bin/otserv
